# Generated by https://quicktype.io

from typing import List
from uuid import UUID


class Command:
    title: str
    description: str

    def __init__(self, title: str, description: str) -> None:
        self.title = title
        self.description = description


class CommandList:
    scopes: List[str]
    commands: List[Command]

    def __init__(self, scopes: List[str], commands: List[Command]) -> None:
        self.scopes = scopes
        self.commands = commands


class Bot:
    bot_id: UUID
    scopes: List[str]
    is_notification_only: bool
    supports_calling: bool
    supports_video: bool
    supports_files: bool
    command_lists: List[CommandList]

    def __init__(self, bot_id: UUID, scopes: List[str], is_notification_only: bool, supports_calling: bool, supports_video: bool, supports_files: bool, command_lists: List[CommandList]) -> None:
        self.bot_id = bot_id
        self.scopes = scopes
        self.is_notification_only = is_notification_only
        self.supports_calling = supports_calling
        self.supports_video = supports_video
        self.supports_files = supports_files
        self.command_lists = command_lists


class Description:
    short: str
    full: str

    def __init__(self, short: str, full: str) -> None:
        self.short = short
        self.full = full


class Developer:
    name: str
    website_url: str
    privacy_url: str
    terms_of_use_url: str

    def __init__(self, name: str, website_url: str, privacy_url: str, terms_of_use_url: str) -> None:
        self.name = name
        self.website_url = website_url
        self.privacy_url = privacy_url
        self.terms_of_use_url = terms_of_use_url


class Icons:
    outline: str
    color: str

    def __init__(self, outline: str, color: str) -> None:
        self.outline = outline
        self.color = color


class AppManifest:
    schema: str
    manifest_version: str
    version: str
    id: UUID
    package_name: str
    developer: Developer
    icons: Icons
    name: Description
    description: Description
    accent_color: str
    bots: List[Bot]
    permissions: List[str]
    valid_domains: List[str]

    def __init__(self, schema: str, manifest_version: str, version: str, id: UUID, package_name: str, developer: Developer, icons: Icons, name: Description, description: Description, accent_color: str, bots: List[Bot], permissions: List[str], valid_domains: List[str]) -> None:
        self.schema = schema
        self.manifest_version = manifest_version
        self.version = version
        self.id = id
        self.package_name = package_name
        self.developer = developer
        self.icons = icons
        self.name = name
        self.description = description
        self.accent_color = accent_color
        self.bots = bots
        self.permissions = permissions
        self.valid_domains = valid_domains
